name: tech_local_storage
description: 本地存储方案 — SharedPreferences、文件读写、Hive 数据库
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  path_provider: ^2.1.0
  go_router: ^14.0.0
# flutter默认是 permission_handler 12.0.3
# 在鸿蒙环境是 flutter_permission_handler: ^10.0.0
  permission_handler: ^12.0.1
  interview_core:
    path: ../../common/core
  interview_widgets:
    path: ../../common/widgets
